import datetime
#print(dir(datetime.date))
print("Print today:",datetime.date.today())
print("Print day:",datetime.date.month)
x=datetime.datetime.now()
print("Print datetime now:",x)
print("Print year:",x.year)
print("Print month:",x.month)
print("Print day:",x.day)
print("Print today:",x.today())
print("Week days:",x.strftime("%A"))
print("Week days:",x.weekday())
demo_dt = datetime.datetime(2020, 5, 17)
print(demo_dt)
print(demo_dt.strftime("%B"))